### ISSUE TITLE
Video Quality Guide

### ISSUE THREAD

**Issue by j-schwartz** [rachelproject/contentshell#1]
Video:
    Maximum Dimensions: 696x392 (under "Picture Settings", I actually set it to 700x392, but it comes out 696)
    x264 Constant Quality RF: 32 (slider on the main pane)
    x264 Preset: medium, Tune: none (dropdown on the main pane)
    H.264 Profile: baseline, Level: 3.0 (dropdown on the main pane) 
    Fast Decode, Web Optimized (checkboxes on the main pane)
  Audio:
    AAC Mono 48kbps (under the audio tab)

**Comment by needlestack** [comment]
Purpose: these settings intentionally sacrifice some video/audio quality to achieve minimum file size and maximum playability on underpowered hardware, while still being reasonably legible and audible. They were chosen through my subjective testing using Khan Academy videos.

These settings will work best with Khan style videos (graphics with little movement) and will probably be too aggressive for live-action video, resulting in unreasonably poor video quality. They were also used on the Math Expression videos with good results.

These settings are described in terms of Handbrake 0.9, but can probably be used in some manner with any x264 compression program.

**Comment by needlestack** [comment]
Moved this to module-template wiki:

  https://github.com/rachelproject/module-template/wiki
