### ISSUE TITLE
Latest commit causes RACHEL-Plus front page loading errors

### ISSUE THREAD

**Issue by spatiald** [rachelproject/contentshell#13]
## ERROR CAUSING COMMIT
4311aa46ba3adb255310a2f4baf051bb1dbb0e48

## PROBLEM
Main RACHEL web page doesn't load.  Error thrown in lighttpd error.log:  
```
2016-04-17 13:28:26: (mod_fastcgi.c.2698) FastCGI-stderr: PHP Parse error:  syntax error, unexpected '[' in /media/RACHEL/rachel/common.php on line 158
```

## WORK AROUND
Using last working commit of:
b5770d065af3dba36ae2565abbc939a27f034429

**Comment by needlestack** [comment]
Ah, looks like an issue with PHP < 5.4 -- I've switched from $foo = []; syntax to $foo = array(); syntax - that should do the trick, though I don't have an older PHP around to test on. Re-open if you still have problems!

**Comment by spatiald** [comment]
## Another error, this time with lang.en.php
```
(mod_fastcgi.c.2698) FastCGI-stderr: PHP Parse error:  syntax error, unexpected '[' in /media/RACHEL/rachel/lang/lang.en.php on line 14
``` 
Same result - front page fails to load

## Solution
```
mv /etc/init/procps.conf /etc/init/procps.conf.old # otherwise quite a pkgs won't install
apt-get update; apt-get upgrade
apt-get -y install php5-cgi git-core python-m2crypto php5-sqlite sqlite3 php-pear make
pecl install stem
```
Then created a file called "/etc/php5/conf.d/stem.ini" and added the following:
```
; configuration for php stem module
extension=stem.so
```
Then i had to "fix" the lang.<lang>.php files changing the following line 14-17 from:
```
$lang['months'] = [
    'Null', 'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'
];
```
to
```
$lang['months'] = array(
    'Null', 'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'
);
```
@needlestack Can you incorporate those changes to provide support for our older CAPs?

**Comment by needlestack** [comment]
Sure - just changed it. That was an old file, but I'll try to keep this in mind for future code! I'll also sweep through the new search code for that syntax.
