### ISSUE TITLE
Standardize default admin page login/pass for main page admin

### ISSUE THREAD

**Issue by spatiald** [rachelproject/contentshell#16]
What about changing the default web page admin from root:rachel to root:Rachel+1 or admin:Rachel+1 so that it is more standardized for end-users?  That way end-users are not trying to figure what the password is initially.

**Comment by j-schwartz** [comment]
I like admin / Rachel+1

**Comment by needlestack** [comment]
Agreed, changed. Should we change this on kalite too? We're currently using rachel/rachel for kalite on piOS...

**Comment by spatiald** [comment]
@needlestack Yes.  That will help with standardizing documentation.
