### ISSUE TITLE
Content Organization

### ISSUE THREAD

**Issue by j-schwartz** [rachelproject/contentshell#2]
Is it possible to add header bars with index.php separating content underneath each of them along the following lines:

Positions 000 - 009 are for GENERAL REFERENCE MATERIAL eg. Wikipedia, Wikipedia for Schools

Positions 010 - 029 are for EDUCATIONAL LEARNING MATERIAlS eg. Khan Academy, ck12, MathExpression, OLPC Educational Packages, PhET, Understanding Algebra, UNESCO IICBA

Positions 030 - 049 are for HEALTH MATERIALS eg. Hesperian Health Guides, Khan Academy Health & Medicine, MedlinePlus Medical Encyclopedia

Positions 050 - 069 are for VOCATIONAL SKILL DEVELOPMENT eg. GCFLearnFree.org, MITScratch, PowerTyping, Infonet - Biovision, Practical Action, Music Theory,

Positions 070 - 079 are for ENTERTAINMENT eg. TED Talks, Radiolab

There would just be a black header bar with white text called GENERAL REFERENCE, EDUCATIONAL LEARNING, etc with the modules fitting in underneath them.

**Comment by needlestack** [comment]
I think this has been superseded by the [rachelmods](http://dev.worldpossible.org/cgi/rachelmods.pl) approach - though that side of things needs some work too.
