### ISSUE TITLE
Captive portal redirect on RACHEL-Plus not working

### ISSUE THREAD

**Issue by spatiald** [rachelproject/contentshell#21]
@needlestack The captiveportal-redirect.php was originally written for the CAP.  I was testing some updates last night and can not get the lasted update you posted to the content to work. 

Additionally, the captiveportal-redirect.php file is also part of the USB Recovery shell for the CAP.

**Comment by needlestack** [comment]
Whoops! I pushed that in before it was ready. Just now pushed a working version. Basically the big change was to make it multi-lingual as we got feedback that the page was confusing for Spanish speakers. Where there other issues with contentshell? Or just the bad captiveportal-redirect.php page?

I'm not sure where it should live - the multi-lingual version will have an easier time in contentshell, but let me know what you think. I'm also thinking we will want to add this functionality to the Rachel-Pi at some point?

**Comment by spatiald** [comment]
I am okay adding it to the content shell but you have to add two additional
files to the web root for CAP redirection to function:
pass_ticket.shtml
redirect.shtml

Both of these are used by lighttd to track if a user has already
redirected.  There might be better way to do this on the CAP.  You can see
the redirection code in /usr/local/etc/lighttpd.conf

**Comment by needlestack** [comment]
Can you give me a brief overview of the intended behavior? I've just started looking into how this would work on the RPi, and I'd love to understand how you've addressed it. I see the code, but I'm not sure how it fits together from the perspective of the user...

**Comment by spatiald** [comment]
The original code was written and default part of the CAP.  It took awhile
to fully understand and I probably don't fully understand it now but I
re-wrote some of it to cater to RACHEL.  For instance, instead of going to
the local content portal (which was default CAP), it goes to the page with
our logos.  There was a thought of removing the captive portal but I think
it does a good job at presenting our logos at least once (even as
convoluted as it is).

For the users perspective, they connect to the access point.

There is a rule in iptables that states "-A PREROUTING -i wlan0 -p tcp -m
tcp --dport 80 -j CAPTIVE" which forces the connection to the CAPTIVE table.

The CAPTIVE table states:

> -A CAPTIVE -p tcp -j CAPTIVE_PASSLIST  # Accept tcp connections to the
> those listed in CAPTIVE_PASSLIST (those who connected less than 30 seconds
> ago)
> -A CAPTIVE -p tcp -j CAPTIVE_WHITELIST  # Accept tcp connections to
> CAPTIVE_WHITELIST (192.168.88.1)
> -A CAPTIVE -p tcp -m tcp --dport 80 -j DNAT --to-destination
> 192.168.88.1:82 # If they were not accepted in the previous 2 rules, than
> point them at 192.168.88.1:82
> -A CAPTIVE_WHITELIST -d 192.168.88.1/32 -p tcp -j ACCEPT # adds
> 192.168.88.1 to CAPTIVE_WHITELIST
>

When the access point sees the first attempt of traffic to pass through it,
it redirects to 192.168.88.1:82.  If you look at
/usr/local/etc/lighttpd.conf, the config states:

> $SERVER["socket"] == ":82" {
>     server.document-root = "/media/RACHEL/rachel"
>     url.rewrite-once = ( "^(?!/pass_ticket.shtml)" => "/redirect.shtml" )
> }
>

This code checks if user passed "/pass_ticket.shtml" in the browser and, if
it didn't, then redirect to "/redirect.shtml".  (NOTE:  user.rewrite-once
will rewrite a set of URLs internally in the webserver BEFORE they are
handled and will cause further rewrite rules to be skipped if the
expression was matched)

redirect.shtml will attempt to redirect to the main RACHEL page but in it's
head is javascript to redirect to the main RACHEL page with
"/pass_ticket.shtml" attached.

Because "/pass_ticket.shtml" is attached, the above code redirects to
pass_ticket.shtml successfully and the following code runs from that file:

> iptables -t nat -D CAPTIVE_PASSLIST -p tcp --dport 80 -s $REMOTEADDR -j
> ACCEPT >/dev/null 2>&1
> iptables -t nat -I CAPTIVE_PASSLIST -p tcp --dport 80 -s $REMOTEADDR -j
> ACCEPT >/dev/null 2>&1
> echo $(arp | grep $REMOTEADDR' ' | awk '{print $3}') >
> /var/run/CaptivePortal/$REMOTEADDR
>

This code adds the current user to the CAPTIVE_PASSLIST and echoes the
user's IP list to a file called /var/run/CaptivePortal/<IP>

Because the user is in the CAPTIVE_PASSLIST now...they are allowed to
continue to the RACHEL page "http://my.content" which passes them to
"/captiveportal-redirect.php" in the following code:

> # RACHEL
> $HTTP["host"] =~ "(^|\.)my\.content$" {
>     server.document-root = "/media/RACHEL/rachel"
>     url.rewrite-once = ( "^/(.*)" => "/captiveportal-redirect.php" )
> }
>

**Comment by needlestack** [comment]
Thanks so much for this explanation! I imagine that would have taken me a very long time to figure out :) There are some times the captive portal thing confuses users, so I am trying to understand the UI flow, and this helps a lot.
