### ISSUE TITLE
Storage Usage Not Updating After Module Removal

### ISSUE THREAD

**Issue by j-schwartz** [rachelproject/contentshell#37]
I have two devices, which I removed a bunch of modules from.  One device dropped down to 254GB used, the other is stuck at 399GB used, despite the removal of the same modules.  The affected device is A4AF85.  I can leave online if you want.

**Comment by needlestack** [comment]
Yeah, let me take a look. Can I see the one that dropped to 254GB as well so I can compare?

**Comment by needlestack** [comment]
Ah, ok. I guess I just mainly wanted to know which modules you deleted so I can see if they got completely removed...

**Comment by j-schwartz** [comment]
everything from en-hesperian_health down on the install.php page.

**Comment by j-schwartz** [comment]
though I just now realized, it obviously wasn't removed because I can see them again!

**Comment by j-schwartz** [comment]
I feel like it gets hung on en-worldmap_10

**Comment by j-schwartz** [comment]
Ignore this, working now.

**Comment by needlestack** [comment]
Yeah, removing that will take a very long time - there's 1.3 million files in there. I don't see why it wouldn't work eventually though. Is it possible it was just taking a very long time?

**Comment by j-schwartz** [comment]
Yes, I'm sure that was it.

**Comment by needlestack** [comment]
You know, worldmap might be a good candidate to repackage as a zim file like we do with en-wikihow... it'll just be one big file then, and a bit easier to work with.

**Comment by needlestack** [comment]
Oh, but it can't - kiwix doesn't support scripts and that relies on some php scripts...
