### ISSUE TITLE
Modules fail to display after update to commit a007835

### ISSUE THREAD

**Issue by spatiald** [rachelproject/contentshell#5]
## Background
Working commit: ```a007835```

Updated to commit: ```2e6f273```

## Problem
Modules fail to display that are in the correct folder and displayed prior to updating

## Temporary Solution for CAPs:
- Log in via ssh
- Run the following commands
```bash
cd /media/RACHEL/rachel
git reset --hard a007835
```

**Comment by bnordha** [comment]
resolved the problem for me

**Comment by j-schwartz** [comment]
One note: for search to work on the rpi you need to run the following from the command line on
an internet-connected system:

      apt-get update
      apt-get install php5-sqlite

I'll see about getting this pre-installed on future versions of RACHEL.

Yeah, the pi is pretty neat. I was wondering how easy it is for you to add stuff to the build - the new modular search is going to rely on sqlite (php-sqlite in particular). I'm using the OYA as just a test case. Seems to work reasonably well. And indexing is scriptable from the command line and very fast. Still need to round off some edges to make it more user friendly but it works pretty well.

Actually, for multi-lingual search support I wanted to know if it's hard to add another php module to the build process. You'd have to do the following:

    apt-get install php-pear
    apt-get install php5-dev
    pecl install stem

There's a few times you have to hit enter in there. And then, as it states at the end of the install, you have to add the following line:

extension=stem.so

To the following files:

/etc/php5/cli/php.ini
/etc/php5/apache2/php.ini

I don't know if it matters, but I add it right above the following lines:

;;;;;;;;;;;;;;;;;;;
; Module Settings ;
;;;;;;;;;;;;;;;;;;;

It sounds like Sam has made some nice improvements on the build process? Perhaps he can fit all that into things automatically? It'll take up a couple hundred extra MB - not sure how critical that is.

(Just noticed a bug whereby the first time you use it you must visit admin.php once to init the DB or the index page will be blank - I'll fix that next...)

Cheers,
Jonathan

**Comment by j-schwartz** [comment]
Those comments were from various jfield notes... I can't get stem to install, but installing sqlite, manually navigating to my.content/admin.php; using login root/rachel ended up getting me up and running with his dynamic index page

**Comment by needlestack** [comment]
It looks like sqlite is part of the rachelplus install now - is this resolved?

**Comment by needlestack** [comment]
Also - it looks like the PHP stem module isn't there yet - that is required for the new self-contained search that we're using on some modules (and more in the future). I'll add that as an issue for rachelplus...

**Comment by spatiald** [comment]
I haven't tested those changes yet...will get back to you

**Comment by needlestack** [comment]
Sounds like this is all worked out from your latest emails - want to close it?

**Comment by spatiald** [comment]
Working with latest configure script...had to install some packages to support the changes; in particular, PHP-pear, gcc-multilib, and sqlite3
